/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Api
 * ECU Vehicle Monitoring API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Request an OTP to email (registers if new)
 */
export const requestOtpBody = zod.object({
  "email": zod.string()
})

export const requestOtpResponse = zod.object({
  "message": zod.string().optional()
})


/**
 * @summary Verify OTP and log in
 */
export const verifyOtpBody = zod.object({
  "email": zod.string(),
  "otpCode": zod.string()
})

export const verifyOtpResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime({})
})


/**
 * @summary Get current authenticated user
 */
export const getMeResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime({})
})


/**
 * Returns the latest simulated ECU sensor readings
 * @summary Get current ECU sensor data
 */
export const getCurrentEcuDataResponse = zod.object({
  "id": zod.string(),
  "speed": zod.number(),
  "rpm": zod.number(),
  "engineTemp": zod.number(),
  "fuelLevel": zod.number(),
  "batteryVoltage": zod.number(),
  "throttlePosition": zod.number(),
  "coolantTemp": zod.number(),
  "oilPressure": zod.number(),
  "hasFault": zod.boolean(),
  "source": zod.string().describe('simulation or esp32 or external'),
  "createdAt": zod.string().datetime({})
})


/**
 * Accepts real sensor data from an ESP32 or other IoT device
 * @summary Ingest ECU data from ESP32 or external device
 */
export const ingestEcuDataBody = zod.object({
  "speed": zod.number().describe('Vehicle speed in km\/h'),
  "rpm": zod.number().describe('Engine RPM'),
  "engineTemp": zod.number().describe('Engine temperature in Celsius'),
  "fuelLevel": zod.number().describe('Fuel level percentage 0-100'),
  "batteryVoltage": zod.number().describe('Battery voltage in volts'),
  "throttlePosition": zod.number().optional().describe('Throttle position percentage'),
  "coolantTemp": zod.number().optional().describe('Coolant temperature in Celsius'),
  "oilPressure": zod.number().optional().describe('Oil pressure in PSI')
})


/**
 * Returns aggregated vehicle health with fault counts and severity
 * @summary Get overall vehicle health status summary
 */
export const getVehicleStatusResponse = zod.object({
  "overallHealth": zod.string().describe('healthy, warning, critical'),
  "activeFaultCount": zod.number(),
  "criticalFaultCount": zod.number(),
  "warningFaultCount": zod.number(),
  "totalReadings": zod.number(),
  "lastReadingAt": zod.string().datetime({}).nullable(),
  "latestReading": zod.object({
  "id": zod.string(),
  "speed": zod.number(),
  "rpm": zod.number(),
  "engineTemp": zod.number(),
  "fuelLevel": zod.number(),
  "batteryVoltage": zod.number(),
  "throttlePosition": zod.number(),
  "coolantTemp": zod.number(),
  "oilPressure": zod.number(),
  "hasFault": zod.boolean(),
  "source": zod.string().describe('simulation or esp32 or external'),
  "createdAt": zod.string().datetime({})
})
})


/**
 * Returns all active and historical DTCs
 * @summary List all diagnostic trouble codes
 */
export const listDtcsQueryParams = zod.object({
  "active": zod.boolean().optional().describe('Filter by active status'),
  "limit": zod.number().optional().describe('Max records to return')
})

export const listDtcsResponseItem = zod.object({
  "id": zod.string(),
  "code": zod.string().describe('DTC code e.g. P0101'),
  "description": zod.string(),
  "severity": zod.string().describe('critical, warning, info'),
  "system": zod.string().describe('engine, fuel, electrical, cooling, transmission'),
  "isActive": zod.boolean(),
  "detectedAt": zod.string().datetime({}),
  "resolvedAt": zod.string().datetime({}).nullable(),
  "ecuReadingId": zod.string().nullable()
})
export const listDtcsResponse = zod.array(listDtcsResponseItem)


/**
 * @summary Mark a DTC as resolved
 */
export const resolveDtcParams = zod.object({
  "id": zod.string()
})

export const resolveDtcResponse = zod.object({
  "id": zod.string(),
  "code": zod.string().describe('DTC code e.g. P0101'),
  "description": zod.string(),
  "severity": zod.string().describe('critical, warning, info'),
  "system": zod.string().describe('engine, fuel, electrical, cooling, transmission'),
  "isActive": zod.boolean(),
  "detectedAt": zod.string().datetime({}),
  "resolvedAt": zod.string().datetime({}).nullable(),
  "ecuReadingId": zod.string().nullable()
})


/**
 * Returns paginated ECU readings history
 * @summary Get historical ECU readings
 */
export const getHistoryQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of records (default 50)'),
  "offset": zod.number().optional().describe('Offset for pagination')
})

export const getHistoryResponseItem = zod.object({
  "id": zod.string(),
  "speed": zod.number(),
  "rpm": zod.number(),
  "engineTemp": zod.number(),
  "fuelLevel": zod.number(),
  "batteryVoltage": zod.number(),
  "throttlePosition": zod.number(),
  "coolantTemp": zod.number(),
  "oilPressure": zod.number(),
  "hasFault": zod.boolean(),
  "source": zod.string().describe('simulation or esp32 or external'),
  "createdAt": zod.string().datetime({})
})
export const getHistoryResponse = zod.array(getHistoryResponseItem)


/**
 * Returns min/max/avg for each sensor metric
 * @summary Get aggregated stats from historical data
 */
export const getHistoryStatsResponse = zod.object({
  "speed": zod.object({
  "min": zod.number(),
  "max": zod.number(),
  "avg": zod.number(),
  "current": zod.number()
}),
  "rpm": zod.object({
  "min": zod.number(),
  "max": zod.number(),
  "avg": zod.number(),
  "current": zod.number()
}),
  "engineTemp": zod.object({
  "min": zod.number(),
  "max": zod.number(),
  "avg": zod.number(),
  "current": zod.number()
}),
  "fuelLevel": zod.object({
  "min": zod.number(),
  "max": zod.number(),
  "avg": zod.number(),
  "current": zod.number()
}),
  "batteryVoltage": zod.object({
  "min": zod.number(),
  "max": zod.number(),
  "avg": zod.number(),
  "current": zod.number()
})
})


