/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Api
 * ECU Vehicle Monitoring API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthCredentials,
  DiagnosticTroubleCode,
  EcuReading,
  EcuSensorInput,
  ErrorResponse,
  GetHistoryParams,
  HealthStatus,
  HistoryStats,
  ListDtcsParams,
  Register200,
  User,
  VehicleLocation,
  VehicleStatus
} from './generated.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthStatus>> => {
    
    
    return axios.default.get(
      `/healthz`,options
    );
  }




export const getHealthCheckQueryKey = () => {
    return [
    `/healthz`
    ] as const;
    }

    
export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = AxiosError<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Register a new system operator
 */
export const register = (
    authCredentials: AuthCredentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Register200>> => {
    
    
    return axios.default.post(
      `/auth/register`,
      authCredentials,options
    );
  }



export const getRegisterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: AuthCredentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: AuthCredentials}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: AuthCredentials}> = (props) => {
          const {data} = props ?? {};

          return  register(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = AuthCredentials
    export type RegisterMutationError = AxiosError<ErrorResponse>

    /**
 * @summary Register a new system operator
 */
export const useRegister = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: AuthCredentials}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: AuthCredentials},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Sign in via email and password
 */
export const login = (
    authCredentials: AuthCredentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    
    
    return axios.default.post(
      `/auth/login`,
      authCredentials,options
    );
  }



export const getLoginMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: AuthCredentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: AuthCredentials}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: AuthCredentials}> = (props) => {
          const {data} = props ?? {};

          return  login(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = AuthCredentials
    export type LoginMutationError = AxiosError<ErrorResponse>

    /**
 * @summary Sign in via email and password
 */
export const useLogin = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: AuthCredentials}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: AuthCredentials},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Log out current user
 */
export const logout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/auth/logout`,undefined,options
    );
  }



export const getLogoutMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = AxiosError<unknown>

    /**
 * @summary Log out current user
 */
export const useLogout = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get current authenticated user
 */
export const getMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    
    
    return axios.default.get(
      `/auth/me`,options
    );
  }




export const getGetMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = AxiosError<ErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = AxiosError<ErrorResponse>


/**
 * @summary Get current authenticated user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = AxiosError<ErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Returns the latest simulated ECU sensor readings
 * @summary Get current ECU sensor data
 */
export const getCurrentEcuData = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EcuReading>> => {
    
    
    return axios.default.get(
      `/ecu/current`,options
    );
  }




export const getGetCurrentEcuDataQueryKey = () => {
    return [
    `/ecu/current`
    ] as const;
    }

    
export const getGetCurrentEcuDataQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentEcuData>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCurrentEcuData>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentEcuDataQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentEcuData>>> = ({ signal }) => getCurrentEcuData({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentEcuData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCurrentEcuDataQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentEcuData>>>
export type GetCurrentEcuDataQueryError = AxiosError<unknown>


/**
 * @summary Get current ECU sensor data
 */

export function useGetCurrentEcuData<TData = Awaited<ReturnType<typeof getCurrentEcuData>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCurrentEcuData>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCurrentEcuDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Generates a simulated ECU reading, runs fault detection, and stores result
 * @summary Simulate and record a new ECU reading
 */
export const simulateEcuData = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EcuReading>> => {
    
    
    return axios.default.post(
      `/ecu/simulate`,undefined,options
    );
  }



export const getSimulateEcuDataMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simulateEcuData>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof simulateEcuData>>, TError,void, TContext> => {

const mutationKey = ['simulateEcuData'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof simulateEcuData>>, void> = () => {
          

          return  simulateEcuData(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SimulateEcuDataMutationResult = NonNullable<Awaited<ReturnType<typeof simulateEcuData>>>
    
    export type SimulateEcuDataMutationError = AxiosError<unknown>

    /**
 * @summary Simulate and record a new ECU reading
 */
export const useSimulateEcuData = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simulateEcuData>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof simulateEcuData>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSimulateEcuDataMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Accepts real sensor data from an ESP32 or other IoT device
 * @summary Ingest ECU data from ESP32 or external device
 */
export const ingestEcuData = (
    ecuSensorInput: EcuSensorInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EcuReading>> => {
    
    
    return axios.default.post(
      `/ecu/ingest`,
      ecuSensorInput,options
    );
  }



export const getIngestEcuDataMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestEcuData>>, TError,{data: EcuSensorInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof ingestEcuData>>, TError,{data: EcuSensorInput}, TContext> => {

const mutationKey = ['ingestEcuData'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ingestEcuData>>, {data: EcuSensorInput}> = (props) => {
          const {data} = props ?? {};

          return  ingestEcuData(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IngestEcuDataMutationResult = NonNullable<Awaited<ReturnType<typeof ingestEcuData>>>
    export type IngestEcuDataMutationBody = EcuSensorInput
    export type IngestEcuDataMutationError = AxiosError<unknown>

    /**
 * @summary Ingest ECU data from ESP32 or external device
 */
export const useIngestEcuData = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestEcuData>>, TError,{data: EcuSensorInput}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ingestEcuData>>,
        TError,
        {data: EcuSensorInput},
        TContext
      > => {

      const mutationOptions = getIngestEcuDataMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Returns aggregated vehicle health with fault counts and severity
 * @summary Get overall vehicle health status summary
 */
export const getVehicleStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleStatus>> => {
    
    
    return axios.default.get(
      `/ecu/status`,options
    );
  }




export const getGetVehicleStatusQueryKey = () => {
    return [
    `/ecu/status`
    ] as const;
    }

    
export const getGetVehicleStatusQueryOptions = <TData = Awaited<ReturnType<typeof getVehicleStatus>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVehicleStatus>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVehicleStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVehicleStatus>>> = ({ signal }) => getVehicleStatus({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVehicleStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetVehicleStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getVehicleStatus>>>
export type GetVehicleStatusQueryError = AxiosError<unknown>


/**
 * @summary Get overall vehicle health status summary
 */

export function useGetVehicleStatus<TData = Awaited<ReturnType<typeof getVehicleStatus>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVehicleStatus>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetVehicleStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Returns all active and historical DTCs
 * @summary List all diagnostic trouble codes
 */
export const listDtcs = (
    params?: ListDtcsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DiagnosticTroubleCode[]>> => {
    
    
    return axios.default.get(
      `/dtc`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getListDtcsQueryKey = (params?: ListDtcsParams,) => {
    return [
    `/dtc`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListDtcsQueryOptions = <TData = Awaited<ReturnType<typeof listDtcs>>, TError = AxiosError<unknown>>(params?: ListDtcsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDtcs>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDtcsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDtcs>>> = ({ signal }) => listDtcs(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDtcs>>, TError, TData> & { queryKey: QueryKey }
}

export type ListDtcsQueryResult = NonNullable<Awaited<ReturnType<typeof listDtcs>>>
export type ListDtcsQueryError = AxiosError<unknown>


/**
 * @summary List all diagnostic trouble codes
 */

export function useListDtcs<TData = Awaited<ReturnType<typeof listDtcs>>, TError = AxiosError<unknown>>(
 params?: ListDtcsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDtcs>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListDtcsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Mark a DTC as resolved
 */
export const resolveDtc = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DiagnosticTroubleCode>> => {
    
    
    return axios.default.patch(
      `/dtc/${id}/resolve`,undefined,options
    );
  }



export const getResolveDtcMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveDtc>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof resolveDtc>>, TError,{id: string}, TContext> => {

const mutationKey = ['resolveDtc'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveDtc>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  resolveDtc(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResolveDtcMutationResult = NonNullable<Awaited<ReturnType<typeof resolveDtc>>>
    
    export type ResolveDtcMutationError = AxiosError<ErrorResponse>

    /**
 * @summary Mark a DTC as resolved
 */
export const useResolveDtc = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveDtc>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof resolveDtc>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getResolveDtcMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Returns paginated ECU readings history
 * @summary Get historical ECU readings
 */
export const getHistory = (
    params?: GetHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EcuReading[]>> => {
    
    
    return axios.default.get(
      `/history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetHistoryQueryKey = (params?: GetHistoryParams,) => {
    return [
    `/history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getHistory>>, TError = AxiosError<unknown>>(params?: GetHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({ signal }) => getHistory(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getHistory>>>
export type GetHistoryQueryError = AxiosError<unknown>


/**
 * @summary Get historical ECU readings
 */

export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = AxiosError<unknown>>(
 params?: GetHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Returns min/max/avg for each sensor metric
 * @summary Get aggregated stats from historical data
 */
export const getHistoryStats = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HistoryStats>> => {
    
    
    return axios.default.get(
      `/history/stats`,options
    );
  }




export const getGetHistoryStatsQueryKey = () => {
    return [
    `/history/stats`
    ] as const;
    }

    
export const getGetHistoryStatsQueryOptions = <TData = Awaited<ReturnType<typeof getHistoryStats>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHistoryStats>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistoryStats>>> = ({ signal }) => getHistoryStats({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistoryStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHistoryStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getHistoryStats>>>
export type GetHistoryStatsQueryError = AxiosError<unknown>


/**
 * @summary Get aggregated stats from historical data
 */

export function useGetHistoryStats<TData = Awaited<ReturnType<typeof getHistoryStats>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHistoryStats>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHistoryStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Returns current position, heading, speed and last 50 GPS trail points
 * @summary Get current vehicle GPS location and trail
 */
export const getVehicleLocation = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleLocation>> => {
    
    
    return axios.default.get(
      `/ecu/location`,options
    );
  }




export const getGetVehicleLocationQueryKey = () => {
    return [
    `/ecu/location`
    ] as const;
    }

    
export const getGetVehicleLocationQueryOptions = <TData = Awaited<ReturnType<typeof getVehicleLocation>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVehicleLocation>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVehicleLocationQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVehicleLocation>>> = ({ signal }) => getVehicleLocation({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVehicleLocation>>, TError, TData> & { queryKey: QueryKey }
}

export type GetVehicleLocationQueryResult = NonNullable<Awaited<ReturnType<typeof getVehicleLocation>>>
export type GetVehicleLocationQueryError = AxiosError<unknown>


/**
 * @summary Get current vehicle GPS location and trail
 */

export function useGetVehicleLocation<TData = Awaited<ReturnType<typeof getVehicleLocation>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVehicleLocation>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetVehicleLocationQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





